### ISSUE TITLE
Why not Use python-chess?

### ISSUE THREAD

**Issue by rahutchinson** [will042/chess_robot#2]
The use of [python-chess](https://python-chess.readthedocs.io/en/latest/) would be great here. 

This provides: 
- all the chess pieces
- the board visual representation
- all state held.

**Comment by will042** [comment]
Thanks for your suggestion. I just added python-chess for board tracking. I think it would be really interesting to get a chess engine running with it so someone could play against the robotic arm. I just pushed that update, and am working on adding some docstrings today so the code will be a bit more clear.

**Comment by will042** [comment]
Resolved.
